// @sk-task geoip-geosite-integration#T1.1: geosite proto schema (v2fly format)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: geosite.proto

package geoip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Domain_Type int32

const (
	Domain_Plain  Domain_Type = 0
	Domain_Regex  Domain_Type = 1
	Domain_Domain Domain_Type = 2
	Domain_Full   Domain_Type = 3
)

// Enum value maps for Domain_Type.
var (
	Domain_Type_name = map[int32]string{
		0: "Plain",
		1: "Regex",
		2: "Domain",
		3: "Full",
	}
	Domain_Type_value = map[string]int32{
		"Plain":  0,
		"Regex":  1,
		"Domain": 2,
		"Full":   3,
	}
)

func (x Domain_Type) Enum() *Domain_Type {
	p := new(Domain_Type)
	*p = x
	return p
}

func (x Domain_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Domain_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_geosite_proto_enumTypes[0].Descriptor()
}

func (Domain_Type) Type() protoreflect.EnumType {
	return &file_geosite_proto_enumTypes[0]
}

func (x Domain_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Domain_Type.Descriptor instead.
func (Domain_Type) EnumDescriptor() ([]byte, []int) {
	return file_geosite_proto_rawDescGZIP(), []int{2, 0}
}

type GeoSiteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         []*GeoSite             `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoSiteList) Reset() {
	*x = GeoSiteList{}
	mi := &file_geosite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoSiteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoSiteList) ProtoMessage() {}

func (x *GeoSiteList) ProtoReflect() protoreflect.Message {
	mi := &file_geosite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoSiteList.ProtoReflect.Descriptor instead.
func (*GeoSiteList) Descriptor() ([]byte, []int) {
	return file_geosite_proto_rawDescGZIP(), []int{0}
}

func (x *GeoSiteList) GetEntry() []*GeoSite {
	if x != nil {
		return x.Entry
	}
	return nil
}

type GeoSite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryCode  string                 `protobuf:"bytes,1,opt,name=category_code,json=categoryCode,proto3" json:"category_code,omitempty"`
	Domain        []*Domain              `protobuf:"bytes,2,rep,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoSite) Reset() {
	*x = GeoSite{}
	mi := &file_geosite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoSite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoSite) ProtoMessage() {}

func (x *GeoSite) ProtoReflect() protoreflect.Message {
	mi := &file_geosite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoSite.ProtoReflect.Descriptor instead.
func (*GeoSite) Descriptor() ([]byte, []int) {
	return file_geosite_proto_rawDescGZIP(), []int{1}
}

func (x *GeoSite) GetCategoryCode() string {
	if x != nil {
		return x.CategoryCode
	}
	return ""
}

func (x *GeoSite) GetDomain() []*Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type Domain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type          Domain_Type            `protobuf:"varint,2,opt,name=type,proto3,enum=geoip.Domain_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_geosite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_geosite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_geosite_proto_rawDescGZIP(), []int{2}
}

func (x *Domain) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Domain) GetType() Domain_Type {
	if x != nil {
		return x.Type
	}
	return Domain_Plain
}

var File_geosite_proto protoreflect.FileDescriptor

const file_geosite_proto_rawDesc = "" +
	"\n" +
	"\rgeosite.proto\x12\x05geoip\"3\n" +
	"\vGeoSiteList\x12$\n" +
	"\x05entry\x18\x01 \x03(\v2\x0e.geoip.GeoSiteR\x05entry\"U\n" +
	"\aGeoSite\x12#\n" +
	"\rcategory_code\x18\x01 \x01(\tR\fcategoryCode\x12%\n" +
	"\x06domain\x18\x02 \x03(\v2\r.geoip.DomainR\x06domain\"z\n" +
	"\x06Domain\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.geoip.Domain.TypeR\x04type\"2\n" +
	"\x04Type\x12\t\n" +
	"\x05Plain\x10\x00\x12\t\n" +
	"\x05Regex\x10\x01\x12\n" +
	"\n" +
	"\x06Domain\x10\x02\x12\b\n" +
	"\x04Full\x10\x03B5Z3github.com/bzdvdn/kvn-ws/src/internal/routing/geoipb\x06proto3"

var (
	file_geosite_proto_rawDescOnce sync.Once
	file_geosite_proto_rawDescData []byte
)

func file_geosite_proto_rawDescGZIP() []byte {
	file_geosite_proto_rawDescOnce.Do(func() {
		file_geosite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geosite_proto_rawDesc), len(file_geosite_proto_rawDesc)))
	})
	return file_geosite_proto_rawDescData
}

var file_geosite_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_geosite_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_geosite_proto_goTypes = []any{
	(Domain_Type)(0),    // 0: geoip.Domain.Type
	(*GeoSiteList)(nil), // 1: geoip.GeoSiteList
	(*GeoSite)(nil),     // 2: geoip.GeoSite
	(*Domain)(nil),      // 3: geoip.Domain
}
var file_geosite_proto_depIdxs = []int32{
	2, // 0: geoip.GeoSiteList.entry:type_name -> geoip.GeoSite
	3, // 1: geoip.GeoSite.domain:type_name -> geoip.Domain
	0, // 2: geoip.Domain.type:type_name -> geoip.Domain.Type
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_geosite_proto_init() }
func file_geosite_proto_init() {
	if File_geosite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geosite_proto_rawDesc), len(file_geosite_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geosite_proto_goTypes,
		DependencyIndexes: file_geosite_proto_depIdxs,
		EnumInfos:         file_geosite_proto_enumTypes,
		MessageInfos:      file_geosite_proto_msgTypes,
	}.Build()
	File_geosite_proto = out.File
	file_geosite_proto_goTypes = nil
	file_geosite_proto_depIdxs = nil
}
